# Install via
# bundle install --path vendor/gems
#
# See http://bombasticmonkey.com/2011/11/04/test-your-puppet-modules-functions/
source :rubygems
# < 0.13 works around a bug in rspec that
# will be fixed with the next release.
gem 'mocha',        '< 0.13'
gem 'puppet',       '>= 3.1.1'
gem 'facter',       '>= 1.6.10'
gem 'puppet-lint'
# we want a special version of rspec-puppet which uses additional hiera lookup
gem 'rspec-puppet', :git => "https://github.com/agx/rspec-puppet.git"
gem 'rake',         '>= 0.9.2'
gem 'puppetlabs_spec_helper', '0.3.0'
